import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :planning_poker, PlanningPokerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Use real UserTrackingContext implementation in production
config :planning_poker, :user_tracking_impl, PlanningPoker.UserTrackingContext

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :sentry,
  environment_name: :prod,
  traces_sample_rate: 0.2,
  enable_source_code_context: true,
  client: PlanningPoker.SentryReqClient
